In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.optimizers import Adam
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.preprocessing import scale
from sklearn.ensemble import RandomForestRegressor 
import re
from sklearn.linear_model import LinearRegression
import sys
from sklearn.linear_model import LogisticRegression
sys.path.append("./")
from basic_feature import *
from my_models import *
import warnings
warnings.filterwarnings("ignore",category=FutureWarning)
train = pd.read_csv("./train.csv")
train = train.dropna(subset=["賃料"])
train = train.drop(20926)
train_x = train.drop("賃料",axis=1)
train_y = train["賃料"]

Using TensorFlow backend.


In [2]:

# bms = bin_model_score(threshold=500000)
# bms.fit(train_x,train_y)


In [3]:
scores = cross_val_score(bin_model_score(is_log=True,threshold=200000),train_x,train_y,scoring="neg_mean_squared_error")

[11:43:06] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:43:15] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:43:19] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:43:35] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:43:44] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:43:48] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:44:05] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:44:14] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[11:44:19] WARNING: src/objective/regression_obj.cu:152: reg:linear is n

In [4]:
print(np.sqrt(-np.array(scores)))
#面積log取らないバージョン
#閾値0.9
#RandomForestとXGBの加重平均
#なんかマシになったぽい

[28589.62943064 25015.87838041 23599.31871877]


In [4]:
print(np.sqrt(-np.array(scores)))
#面積log取らないバージョン
#閾値0.9
#線形回帰バージョン

[31381.11240831 27982.9626141  29498.70232022]


In [4]:
print(np.sqrt(-np.array(scores)))
#面積log取らないバージョン
#閾値0.9
#ランダムフォレストとの比較のためXGBをチューニングなしでぶっこんだ

[29764.36251439 25737.75956184 25349.00059902]


In [4]:
print(np.sqrt(-np.array(scores)))
#面積log取らないバージョン
#閾値0.9
#ランダムフォレスト

[27486.14989315 25699.20269982 23611.26902551]


In [4]:
print(np.sqrt(-np.array(scores)))
#面積log取らないバージョン
#閾値0.9

[25937.72924312 22154.03019855 20517.2577945 ]


In [3]:
# print(np.sqrt(-np.array(scores)))
#面積log取らないバージョン

[25373.97640343 21073.2302127  19278.75458529]


In [4]:
# print(np.sqrt(-np.array(scores)))
# #アンサンブルになってなかった(モデルの引数が違った)
# #直した

[25357.52421909 21447.1391929  18449.84829596]


In [4]:
# print(np.sqrt(-np.array(scores)))
#分類モデルの閾値を0.5→0.3にむしろ下げた
#たいして変わらないが、分類の影響はこのあたりが限界っぽい。

[25055.61403267 21372.70426949 18621.98159184]


In [4]:
# print(np.sqrt(-np.array(scores)))
#分類モデルの閾値を0.5→0.95に
#精度は悪化したが、過学習感は薄れたか?
#ほんとに?

[27954.54367869 23115.85356113 26778.12061267]


In [4]:
# print(np.sqrt(-np.array(scores)))
#分類モデルの確立でミックスしたら全然うまくいかんかった。

[140848.6346678  139520.96292192 137773.88130604]


In [5]:
# print(np.sqrt(-np.array(scores)))

[24869.19273447 20853.49119503 17830.20135745]


In [6]:
bms = bin_model_score(threshold=200000)
bms.fit(train_x,train_y)

[01:30:12] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:30:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:30:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:30:46] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:31:06] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [7]:
rm = bms.rich_model
pm = bms.poor_model

In [4]:
m1,m2,m3 = pre_checker(train_x,train_y)

In [5]:
m1.predict(train).head()

areasize  is_large  area_sq  room  L  D  K  S       apr  year  ...  dist18  \
0  2.996232         0      4.0     1  0  0  1  0  2.996232     9  ...     0.0   
1  2.803360         0      4.0     1  0  0  0  0  2.803360    44  ...     0.0   
2  3.093313         0      5.0     1  0  0  1  0  3.093313     8  ...     0.0   
3  4.102313         0      8.0     2  1  1  1  0  2.051156    29  ...     0.0   
4  3.680343         0      6.0     2  0  1  1  0  1.840172    31  ...     0.0   

   dist19  dist20  dist21  dist22  walk    avgwalk  park0  park1  park2  
0     0.0     0.0     0.0     0.0     4   8.333333      1      0      0  
1     0.0     0.0     0.0     0.0     5  11.333333      1      0      0  
2     0.0     0.0     0.0     0.0     6  10.000000      1      0      1  
3     0.0     0.0     0.0     0.0     9   8.666667      0      0      0  
4     0.0     1.0     0.0     0.0     5   9.666667      0      0      0  

[5 rows x 44 columns]

In [8]:
m1.predict(train).columns

Index(['areasize', 'is_large', 'area_sq', 'room', 'L', 'D', 'K', 'S', 'apr',
       'year', 'year_cat', 'what_floor', 'height_bld', 'height_percent',
       'istower', 'ishigh', 'dist0', 'dist1', 'dist2', 'dist3', 'dist4',
       'dist5', 'dist6', 'dist7', 'dist8', 'dist9', 'dist10', 'dist11',
       'dist12', 'dist13', 'dist14', 'dist15', 'dist16', 'dist17', 'dist18',
       'dist19', 'dist20', 'dist21', 'dist22', 'walk', 'avgwalk', 'park0',
       'park1', 'park2'],
      dtype='object')

In [19]:
rm[-1].get_booster().get_score(importance_type='weight')

{'areasize': 833,
 'dist16': 83,
 'year': 331,
 'dist15': 72,
 'height_bld': 239,
 'avgwalk': 329,
 'dist4': 25,
 'what_floor': 192,
 'walk': 162,
 'apr': 333,
 'dist17': 41,
 'room': 28,
 'dist14': 29,
 'dist3': 22,
 'height_percent': 129,
 'S': 14,
 'dist1': 9,
 'dist10': 16,
 'dist9': 7,
 'dist5': 15,
 'L': 10,
 'park2': 17,
 'dist0': 6,
 'dist11': 16,
 'dist8': 16,
 'park1': 44,
 'dist19': 16,
 'dist2': 10,
 'park0': 27,
 'dist6': 22,
 'dist7': 13,
 'dist22': 11,
 'dist12': 9,
 'dist18': 7,
 'D': 3}

In [55]:
ans.to_csv("bin_type_fe1.csv",header=False,index=False)

In [59]:
grid_params2={
    "xgb__n_estimators":[100,120,140],
    "xgb__max_depth":[7,8,9],
    "xgb__min_child_weight":[0,5,15],
    "xgb__learning_rate":[0.1,0.2],
    "xgb__random_state":[7777]
}
GCV2 = GridSearchCV(
    Pipeline(steps=rich_step),
    grid_params2,
    cv = 3,
    scoring="neg_mean_squared_error",
    verbose=3
)
GCV2.fit(temp_x_rich,temp_y_rich)

Fitting 3 folds for each of 54 candidates, totalling 162 fits
[CV] xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=100, xgb__random_state=7777 
[17:05:14] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=100, xgb__random_state=7777, score=-20533275032.002, total=   0.6s
[CV] xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=100, xgb__random_state=7777 
[17:05:14] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s


[CV]  xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=100, xgb__random_state=7777, score=-15907774518.319, total=   0.6s
[CV] xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=100, xgb__random_state=7777 
[17:05:15] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.3s remaining:    0.0s


[CV]  xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=100, xgb__random_state=7777, score=-9381239329.321, total=   0.6s
[CV] xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=120, xgb__random_state=7777 
[17:05:16] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=120, xgb__random_state=7777, score=-20454789224.898, total=   0.7s
[CV] xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=120, xgb__random_state=7777 
[17:05:16] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_child_weight=0, xgb__n_estimators=120, xgb__random_state=7777, score=-15826305572.156, total=   0.9s
[CV] xgb__learning_rate=0.1, xgb__max_depth=7, xgb__min_c

[Parallel(n_jobs=1)]: Done 162 out of 162 | elapsed:  2.2min finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('drop_id',
                                        <my_class.drop_id object at 0x134b3b690>),
                                       ('parse_area',
                                        <my_class.parse_area_size object at 0x136792550>),
                                       ('parse_room',
                                        <my_class.parse_rooms object at 0x136792a50>),
                                       ('parse_old',
                                        <my_class.parse_how_old object at 0x136792990>),
                                       ('str_label',
                                        <my_class.structure_lab...
                                                     seed=None, silent=None,
                                                     subsample=1,
                                                     verbosity=1))],
         

In [810]:
crazy_pred = crazy["賃料"].median()
print(crazy_pred)
pred = pd.DataFrame([crazy_pred for i in range(len(crazy.index))])
print(np.sqrt(mean_squared_error(crazy["賃料"],pred)))

650000.0
301848.99189789325
